### ISSUE TITLE
Typo in file names

### ISSUE THREAD

**Issue by xfishbonex** [Magisk-Modules-Repo/SanFrancisco_Fonts#1]
Please check the names for:

- `Roboto-BoldhItalic.ttf`
- `Roboto-LightItalic..ttf`

![image](https://user-images.githubusercontent.com/16347198/52570134-c710a280-2e23-11e9-83d7-69b574ce5a5e.png)

**Comment by cptmacp** [comment]
fixed , thanks a lot @xfishbonex
