### ISSUE TITLE
Problem in Google Chrome

### ISSUE THREAD

**Issue by Kucharskov** [Magisk-Modules-Repo/SanFrancisco_Fonts#10]
Hi! Ive installed latest version of module and have strange problem on some websites eg this: https://pl.gadget-info.com/65323-15-best-magisk-modules-you-should-use

Without module:
![IMG_20191107_100525](https://user-images.githubusercontent.com/2500114/68375076-6d38d100-0146-11ea-9b9c-cd842c868ae6.jpg)

With module:
![IMG_20191107_100540](https://user-images.githubusercontent.com/2500114/68375103-79249300-0146-11ea-8193-8a639cc4af64.jpg)

Any way to fix that issue?

**Comment by cptmacp** [comment]
[SanFrancisco_Fonts_w_o_emoji_By_Apple.Inc-v4.0 - working- Copy.zip](https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/files/3823576/SanFrancisco_Fonts_w_o_emoji_By_Apple.Inc-v4.0.-.working-.Copy.zip)


please try this and let me know

**Comment by Kucharskov** [comment]
That's working fine right now. Could you tell me what did you change?

**Comment by cptmacp** [comment]
Roboto Bold , Changed Metric alignment to 5%
