### ISSUE TITLE
Module not working on pie. Device details below

### ISSUE THREAD

**Issue by adityasubathu** [Magisk-Modules-Repo/SanFrancisco_Fonts#4]
Xiaomi Redmi Note 4, Android Pie based Lineage OS 16, Treble A only. Pix3lify is able to install Google Sans as system font. But not San Fransisco Fonts. Please tell me of there's a solution already.

**Comment by cptmacp** [comment]
please elaborate your issue properly .
the module is not being installed ?
or you cant see the font difference 




Xiaomi Redmi Note 4, Android Pie based Lineage OS 16, Treble A only. Pix3lify is able to install Google Sans as system font. But not San Fransisco Fonts. Please tell me of there's a solution already.



> 
> 
> Xiaomi Redmi Note 4, Android Pie based Lineage OS 16, Treble A only. Pix3lify is able to install Google Sans as system font. But not San Fransisco Fonts. Please tell me of there's a solution already.

**Comment by adityasubathu** [comment]
The module installs successfully. But fonts are still the same after reboot.

**Comment by cptmacp** [comment]
> 
> 
> The module installs successfully. But fonts are still the same after reboot.

please visit here from the phone ( magisk manager )

[![N|Solid](https://i.imgur.com/Xzose2Y.jpg)]()

if you see the apple logo  in todos then fonts are system wide and working
or else there is some sort of issue with your rom , maybe try to remove module ( uninstall magisk and install it again )

**Comment by adityasubathu** [comment]
The module works fine on oreo (same a only treble partition, los rom) and other font changers are working fine. Is there a way to log the installation?

**Comment by adityasubathu** [comment]
Nevermind. It worked after I updated my ROM to a newer version. It's still not working on the older versions, tho. Thanks anyway.
