### ISSUE TITLE
Android Q / P Lockscreen Bug

### ISSUE THREAD

**Issue by Eamo5** [Magisk-Modules-Repo/SanFrancisco_Fonts#5]
Google Pixel 2 XL on Android Q Beta 3. Issue also appeared to occur on P if I recall correctly. Screenshot attached below.
![Screenshot_20190525-191734](https://user-images.githubusercontent.com/40135614/58367387-1c058f80-7ece-11e9-98c9-70e57f70645e.png)

**Comment by cptmacp** [comment]
clock uses a different glyph from google's Source Sans Font 
so need to add that glyph to make the [] go away and it should show :  
actually [] is used as a default , when the glyph is not found 
its like a fallback character

**Comment by Eamo5** [comment]
> clock uses a different glyph from google's Source Sans Font
> so need to add that glyph to make the [] go away and it should show :
> actually [] is used as a default , when the glyph is not found
> its like a fallback character

I figured so much, sounds like a relatively easy fix. Looking forward to an update so I can escape Google Sans ASAP :laughing:

**Comment by Eamo5** [comment]
Can confirm this is now fixed. Thanks!

**Comment by cptmacp** [comment]
> Can confirm this is now fixed. Thanks!

glad to know 
thanks for feedback !

**Comment by Eamo5** [comment]
Hate to be the bearer of [bad news](https://i.imgur.com/iXd1gdl.png) but...

**Comment by cptmacp** [comment]
> Hate to be the bearer of [bad news](https://i.imgur.com/iXd1gdl.png) but...

oh yea , this happened few updates back , need to see ttf does that :D
ill fix and push update

**Comment by cptmacp** [comment]
> Hate to be the bearer of [bad news](https://i.imgur.com/iXd1gdl.png) but...

updated module try now , it should be fixed

**Comment by Eamo5** [comment]
Yep I can confirm the module appears to be working flawlessly now. Thanks for your help!

**Comment by cptmacp** [comment]
glad !
also thanks again for feedback and debugging

**Comment by rpettersonn** [comment]
![Screenshot_20191106-163156_Chrome_Dev](https://user-images.githubusercontent.com/57459244/68331224-62812c00-00b3-11ea-89b2-0832356be680.png)
Help

**Comment by cptmacp** [comment]
@rpettersonn 

try this and report back 

https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/files/3815520/SanFrancisco_Fonts_w_o_emoji_By_Apple.Inc-v4.0.-.working-.Copy.zip

**Comment by rpettersonn** [comment]
Working, thanks,. have this fix with emojis?
