### ISSUE TITLE
Info in Magisk

### ISSUE THREAD

**Issue by lucenera** [Magisk-Modules-Repo/SanFrancisco_Fonts#6]
There is a problem displaying the module information in the latest version of Magisk Manager.
![Screenshot_20190602-062941_Manager](https://user-images.githubusercontent.com/35407790/58756808-df561b80-84ff-11e9-8b0a-92676ea99f49.jpg)
For all other modules the information is displayed correctly.

**Comment by cptmacp** [comment]
for some reason ,only my module is been shown as ' rich text file '
i deleted and added dummy module , still didnt fix , not sure what to do , im asking module mainatiners

**Comment by cptmacp** [comment]
issue is fixed now , and everything seems to work 
@lucenera
