### ISSUE TITLE
How to Fix Colon Issues for Another Font?

### ISSUE THREAD

**Issue by velitasali** [Magisk-Modules-Repo/SanFrancisco_Fonts#7]
Hi, 

I am working on a customized version of Ubuntu font on Android. The font is based on Roboto Regular to fix alignment issues and I have a colon issue. I am opening this here because it is stated in the README that this font doesn't have that issue, so I am guessing you might know how to fix it. Any help would be appreciated. 

I am leaving the font below so you can look at it. I am using FontLab VI. 

Thanks in advance. 

[Ubuntu Font for Android Magisk.zip](https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/files/3293933/Ubuntu.Font.for.Android.Magisk.zip)

**Comment by cptmacp** [comment]
add the colon " : " over U+EE01 glyph

**Comment by velitasali** [comment]
Thanks for quick reply. It did the trick. 
[a-mod.zip](https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/files/3294000/a-mod.zip)

![Screenshot_20190616-123603](https://user-images.githubusercontent.com/10258162/59562299-a9eb1b00-9033-11e9-9427-0ba36844ea3b.png)
