### ISSUE TITLE
":" char not displayed correctly

### ISSUE THREAD

**Issue by dreamwhite** [Magisk-Modules-Repo/SanFrancisco_Fonts#9]
Phone: OnePlus 6T
Android version: 9
OxygenOS version: 9.0.17
Magisk version: 20.1
Magisk Manager version: 7.4.0

After updating with latest version available

https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/releases/download/4.0/SanFrancisco_Fonts_w_emoji_By_Apple.Inc-v4.0.zip

I noticed that the ":" char is displayed with some horizontal bars. With previous version it worked.

**Comment by dreamwhite** [comment]
![Screenshot_20191106-072348](https://user-images.githubusercontent.com/17933708/68273860-dc8bc380-0067-11ea-8bde-791986e0bb1b.jpg)

**Comment by cptmacp** [comment]
this looks like light font been used in oos 

try this and tell me if it fixes the issue

[SanFrancisco_Fonts_w_o_emoji_By_Apple.Inc-v4.0 - Copy.zip](https://github.com/Magisk-Modules-Repo/SanFrancisco_Fonts/files/3814520/SanFrancisco_Fonts_w_o_emoji_By_Apple.Inc-v4.0.-.Copy.zip)

**Comment by s4msy** [comment]
This fixed the issue. Had the same error as OP, same setting but different phone. (Sony xa2) and LOS 16.

**Comment by dreamwhite** [comment]
Okay it seems fixed with this version. But why it doesn't work with v4.0? Is there any chance to get it work?

**Comment by cptmacp** [comment]
the sf fonts are reworked a lot 
the em size is changed very heavily and it causes a lot of display part to get fucked up 

closing the issue , please make a new issue if any other bug is found

**Comment by tiarap00** [comment]
Sorry, had the same issue on op6 and this one solved the problem, is it's available also with emojis? Many thanks.

**Comment by cptmacp** [comment]
@tiarap00   
once all issues ae addressed ill reupload them again .
else you can extract  the NotoColor.ttf from the other emoji varaiant and place it in this new zip 

inside /system/font/ and reflash it 

good luck
